#!/usr/bin/env bash

#
# <-- Autostart -->
#

(
# shortcut server
#
sxhkd &

# This helps to not kill ur eyes
#
redshift &

# Notification daemon
#
dunst &

# Get variables from Xresources
#
xrdb ~/.Xresources &

# Set background
#
xsetroot -solid '#32302f'

# Clipboard manager
#
autocutsel -fork &
autocutsel -fork -selection PRIMARY &
) &

#
# <-- bspwm stuff -->
#


bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Set border color
bspc config normal_border_color '#ebdbb2'
bspc config active_border_color '#817F7F'

